collision.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include `main.h`
*
#include `collision.h`
*
#include `soundwavefunction.h`
*
#include <stdbool.h>
*
Functions
void absorption (item_node *temp, float coeff)
void interference (int x, int y, int z)
bool checkSoundValid (item_node *temp, int x, int y, int z)
Function Documentation
void absorption (item_node * temp, float coeff)
Absorption der Frequenzen um einen Koeffizienten
Parameters
temp Item das reduziert wird
x
y
z
coeff Reduzierungsfaktor
Definition at line 16 of file collision.c.
References getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), and setFreq6000b10000().
Referenced by createReceipt(), and main().
bool checkSoundValid (item_node * temp, int x, int y, int z)
Ungültige SoundItems werden entfernt
Parameters
temp
x
y
z
Returns
Gültigkeit des Wertes
Definition at line 167 of file collision.c.
References getDirectionID(), getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), getItemID(), and removeItem().
Referenced by main().
void interference (int x, int y, int z)
Allgemeine Interferenzen
Parameters
x
y
z
Definition at line 35 of file collision.c.
References createItem(), getDirectionID(), getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), getItem_Root(), getItemID(), getSideOfWave(), getWaveRoot(), item_node::next, setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), setSideOfWave(), and setWaveRoot().
Referenced by main().