extras.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include `main.h`
*
#include `soundwavefunction.h`
*
Functions
void createWall ()
void door ()
void box ()
void loudspeaker ()
Function Documentation
void box ()
Definition at line 49 of file extras.c.
References createItem(), i, j, and k.
void createWall ()
Erzeugt eine Wand komplett um den Raum
Definition at line 8 of file extras.c.
References createItem(), i, j, k, x_format, y_format, and z_format.
void door ()
Definition at line 24 of file extras.c.
References createItem(), i, j, k, x_format, y_format, and z_format.
void loudspeaker ()
Funktion eines Lautsprechers wird simuliert
Definition at line 61 of file extras.c.
References createItem(), i, setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), and setSideOfWave().
Referenced by main().