main.h File Reference
#include <stdbool.h>
*
Data Structures
struct item_node
Typedefs
typedef struct item_node item_node
Functions
int getItemID (item_node *node)
void setItemID (item_node *node, int id)
int getFieldID (int x, int y, int z)
void setFreq20b40 (item_node *node, int value)
void setFreq40b100 (item_node *node, int value)
void setFreq100b150 (item_node *node, int value)
void setFreq150b400 (item_node *node, int value)
void setFreq400b1000 (item_node *node, int value)
void setFreq1000b2000 (item_node *node, int value)
void setFreq2000b3500 (item_node *node, int value)
void setFreq3500b6000 (item_node *node, int value)
void setFreq6000b10000 (item_node *node, int value)
void setFreq10000b20000 (item_node *node, int value)
int getFreq20b40 (item_node *node)
int getFreq40b100 (item_node *node)
int getFreq100b150 (item_node *node)
int getFreq150b400 (item_node *node)
int getFreq400b1000 (item_node *node)
int getFreq1000b2000 (item_node *node)
int getFreq2000b3500 (item_node *node)
int getFreq3500b6000 (item_node *node)
int getFreq6000b10000 (item_node *node)
int getFreq10000b20000 (item_node *node)
void setDirectionID (item_node *node, int value)
int getDirectionID (item_node *node)
item_node * getItem_Root (int x, int y, int z)
item_node * createItem (int x, int y, int z, int id)
item_node * addItem (item_node *node, int x, int y, int z)
void addItemNewRoom (item_node *node, int x, int y, int z)
int isSoundField (int x, int y, int z)
void removeItem (item_node *node)
Variables
int x_format
Raum Formate.
int y_format
int z_format
Typedef Documentation
typedef struct item_node item_node
Alle Elemente werden in Form dieses Structs repräsentiert
Function Documentation
item_node* addItem (item_node * node, int x, int y, int z)
Fügt ein Element an eine neue Stelle (Eigenschaften bleiben erhalten), Element an der alten Position wird entfernt
Parameters
node
x
y
z
Returns
Definition at line 556 of file main.c.
References getItem_Root(), getItemID(), item_node::next, item_node::prev, and removeItem().
void addItemNewRoom (item_node * node, int x, int y, int z)
Fügt ein Element an eine neue Stelle in new_room (Eigenschaften bleiben erhalten), Element an der alten Position wird entfernt
Parameters
node
x
y
z
Definition at line 599 of file main.c.
References getItem_RootNewRoom(), getItemID(), item_node::next, item_node::prev, and removeItem().
Referenced by main(), procedure(), and procedureH().
item_node* createItem (int x, int y, int z, int id)
Erzeugt ein neues Item mit einer bestimmten ID
Parameters
x
y
z
id
Returns
Definition at line 487 of file main.c.
References getItem_Root(), getItemID(), item_node::id, item_node::next, item_node::prev, and setMovement().
Referenced by box(), createReceipt(), createWall(), door(), interference(), loudspeaker(), main(), procedure(), and procedureH().
int getDirectionID (item_node * node)
Gibt die Richtung eine SoundItem
Parameters
node
Returns
Richtung
Definition at line 421 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by addWave(), checkSoundValid(), interference(), main(), prepareArrays(), procedure(), and procedureH().
int getFieldID (int x, int y, int z)
Gibt die allgemeine Feld ID zurück.
Parameters
x
y
z
Returns
0: Sound, 1: Hinderniss, 2: ungültiges Element, 3: leeres Feld (Linked List Head)
Definition at line 218 of file main.c.
References item_node::id, item_node::next, x_format, and y_format.
Referenced by main().
int getFreq10000b20000 (item_node * node)
Definition at line 395 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq1000b2000 (item_node * node)
Definition at line 363 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq100b150 (item_node * node)
Definition at line 339 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq150b400 (item_node * node)
Definition at line 347 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), saveVisualisation(), and setFreqAll().
int getFreq2000b3500 (item_node * node)
Definition at line 371 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq20b40 (item_node * node)
Definition at line 323 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq3500b6000 (item_node * node)
Definition at line 379 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq400b1000 (item_node * node)
Definition at line 355 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq40b100 (item_node * node)
Definition at line 331 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
int getFreq6000b10000 (item_node * node)
Definition at line 387 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), checkSoundValid(), decSoundWithMovement(), interference(), prepareArrays(), and setFreqAll().
item_node* getItem_Root (int x, int y, int z)
Das Root Element ist das 1.Element jeder gültigen Koordinate (ID 3)
Parameters
x
y
z
Returns
Definition at line 465 of file main.c.
References item_node::id, item_node::next, x_format, and y_format.
Referenced by addItem(), createItem(), interference(), main(), saveVisualisation(), and unToucheAll().
int getItemID (item_node * node)
Gibt die ITEM ID zurück.
Parameters
node
Returns
0: Sound, 1: Hinderniss, 2: ungültiges Element
Definition at line 196 of file main.c.
References item_node::id.
Referenced by addItem(), addItemNewRoom(), addWave(), checkSoundValid(), copyMovement(), createItem(), decSoundWithMovement(), getDirectionID(), getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), getMovement(), getSideOfWave(), getTouch(), getWaveRoot(), increaseMovement(), interference(), prepareArrays(), saveVisualisation(), setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), setMovement(), setSideOfWave(), setTouche(), setWaveRoot(), testGetItemID(), unTouche(), and unToucheAll().
int isSoundField (int x, int y, int z)
Prüft ob Feld ein Sound Feld ist
Parameters
x
y
z
Returns
Definition at line 622 of file main.c.
References item_node::id, x_format, and y_format.
Referenced by addWave(), and createReceipt().
void removeItem (item_node * node)
Entfernt das ausgewählte Element
Parameters
node
Definition at line 532 of file main.c.
References item_node::next, and item_node::prev.
Referenced by addItem(), addItemNewRoom(), checkSoundValid(), and main().
void setDirectionID (item_node * node, int value)
Richtung eines SoundItem setzen
Parameters
node
value
Definition at line 410 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by createReceipt(), interference(), loudspeaker(), main(), procedure(), and procedureH().
void setFreq10000b20000 (item_node * node, int value)
Definition at line 315 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq1000b2000 (item_node * node, int value)
Definition at line 291 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq100b150 (item_node * node, int value)
Definition at line 273 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq150b400 (item_node * node, int value)
Definition at line 279 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq2000b3500 (item_node * node, int value)
Definition at line 297 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq20b40 (item_node * node, int value)
Definition at line 261 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq3500b6000 (item_node * node, int value)
Definition at line 303 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq400b1000 (item_node * node, int value)
Definition at line 285 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq40b100 (item_node * node, int value)
Definition at line 267 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setFreq6000b10000 (item_node * node, int value)
Definition at line 309 of file main.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by absorption(), createReceipt(), decSoundWithMovement(), interference(), loudspeaker(), main(), and setFreqAll().
void setItemID (item_node * node, int id)
Gibt einem ITEM die ID
Parameters
node
id
Definition at line 207 of file main.c.
References item_node::id.
Variable Documentation
int x_format
Raum Formate.
Definition at line 17 of file main.c.
Referenced by allocRoom(), changeRoom(), createRoom(), createRoomNew(), createWall(), door(), getFieldID(), getItem_Root(), getItem_RootNewRoom(), isSoundField(), main(), saveVisualisation(), and unToucheAll().
int y_format
Definition at line 18 of file main.c.
Referenced by allocRoom(), createRoom(), createRoomNew(), createWall(), door(), getFieldID(), getItem_Root(), getItem_RootNewRoom(), isSoundField(), main(), saveVisualisation(), and unToucheAll().
int z_format
Definition at line 19 of file main.c.
Referenced by allocRoom(), createRoom(), createRoomNew(), createWall(), door(), main(), saveVisualisation(), and unToucheAll().