minunit_soundsim.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <stdbool.h>
*
#include <string.h>
*
#include `main.h`
*
#include `soundwavefunction.h`
*
#include `collision.h`
*
#include `minunit.h`
*
Functions
static char * testGetItemID ()
static char * all_tests ()
int main (int argc, char **argv)
Variables
int tests_run = 0
int x_format = 100
Raum Formate.
int y_format = 100
int z_format = 100
item_node *** room
item_node *** room_new
item_node * test1
item_node * test2
item_node * test3
Function Documentation
static char* all_tests () [static]
Definition at line 27 of file minunit_soundsim.c.
References mu_run_test, and testGetItemID().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 33 of file minunit_soundsim.c.
References all_tests(), createItem(), createRoom(), setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), setSideOfWave(), tests_run, x_format, and y_format.
static char* testGetItemID () [static]
Definition at line 21 of file minunit_soundsim.c.
References getItemID(), and mu_assert.
Referenced by all_tests().
Variable Documentation
item_node*** room
Definition at line 14 of file minunit_soundsim.c.
item_node*** room_new
Definition at line 15 of file minunit_soundsim.c.
item_node* test1
Definition at line 16 of file minunit_soundsim.c.
item_node* test2
Definition at line 17 of file minunit_soundsim.c.
item_node* test3
Definition at line 18 of file minunit_soundsim.c.
int tests_run = 0
Definition at line 10 of file minunit_soundsim.c.
Referenced by main().
int x_format = 100
Raum Formate.
Definition at line 11 of file minunit_soundsim.c.
Referenced by main().
int y_format = 100
Definition at line 12 of file minunit_soundsim.c.
Referenced by main().
int z_format = 100
Definition at line 13 of file minunit_soundsim.c.