soundwavefunction.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <stdbool.h>
*
#include `main.h`
*
#include `soundwavefunction.h`
*
Functions
void increaseMovement (item_node *node)
int getMovement (item_node *node)
void setMovement (item_node *node, int m)
void copyMovement (item_node *node, item_node *newnode)
void setWaveRoot (item_node *node, item_node *rootnode)
item_node * getWaveRoot (item_node *node)
void setTouche (item_node *node)
void unTouche (item_node *node)
void unToucheAll ()
bool getTouch (item_node *node)
void decSoundWithMovement (item_node *node)
void setSideOfWave (item_node *node, int side)
int getSideOfWave (item_node *node)
void changeReboundSideOfWave (item_node *node)
void setFreqAll (item_node *node, item_node *newnode)
void procedureH (item_node *temp, int x, int y, int z, int side)
void procedure (item_node *temp, int x, int y, int z, int side)
void addWave (item_node *temp, int x, int y, int z)
Variables
int j
int k
int l
Function Documentation
void addWave (item_node * temp, int x, int y, int z)
Welle eines SoundItem wird erzeugt addwave lässt die Welle bis zu einer bestimmten Verschiebungsweite ungekrümmt, danach werden die resultierenden Teilchen `Kugelfunktionsartig` erzeugt und haben eine zugehörgkeit zur rechten oder linken Seite.
Parameters
temp
x
y
z
Definition at line 274 of file soundwavefunction.c.
References getDirectionID(), getItemID(), getMovement(), getSideOfWave(), isSoundField(), procedure(), procedureH(), and setTouche().
Referenced by main().
void changeReboundSideOfWave (item_node * node)
Ähnlich wie Rebound der Teilchen. Seitenzugehörigkeit wird verändert
Parameters
node
Definition at line 182 of file soundwavefunction.c.
References getSideOfWave(), and setSideOfWave().
Referenced by main().
void copyMovement (item_node * node, item_node * newnode)
Kopiert das Movement von einem Item zum anderen
Parameters
node
newnode
Definition at line 45 of file soundwavefunction.c.
References getItemID(), getMovement(), and setMovement().
Referenced by procedure(), and procedureH().
void decSoundWithMovement (item_node * node)
Verringert die Frequenzen während des Movements
Parameters
node
Definition at line 120 of file soundwavefunction.c.
References getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), getItemID(), getMovement(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), and setFreq6000b10000().
Referenced by main().
int getMovement (item_node * node)
Getter für Movement
Parameters
node
Returns
Definition at line 23 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by addWave(), copyMovement(), decSoundWithMovement(), and prepareArrays().
int getSideOfWave (item_node * node)
Getter für die Seite der Welle
Parameters
node
Returns
Definition at line 171 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by addWave(), changeReboundSideOfWave(), interference(), and prepareArrays().
bool getTouch (item_node * node)
Getter für Touched Status
Parameters
node
Returns
Definition at line 109 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by main(), and prepareArrays().
item_node* getWaveRoot (item_node * node)
Definition at line 57 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by interference().
void increaseMovement (item_node * node)
Erhöhung des Movements
Parameters
node
Definition at line 13 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by main().
void procedure (item_node * temp, int x, int y, int z, int side)
Zeugs 2 :D
Parameters
temp
x
y
z
side
Definition at line 253 of file soundwavefunction.c.
References addItemNewRoom(), copyMovement(), createItem(), getDirectionID(), setDirectionID(), setFreqAll(), setSideOfWave(), and setTouche().
Referenced by addWave().
void procedureH (item_node * temp, int x, int y, int z, int side)
Zeugs
Parameters
temp
x
y
z
side
Definition at line 232 of file soundwavefunction.c.
References addItemNewRoom(), copyMovement(), createItem(), getDirectionID(), setDirectionID(), setFreqAll(), setSideOfWave(), setTouche(), and setWaveRoot().
Referenced by addWave().
void setFreqAll (item_node * node, item_node * newnode)
Frequenzen eines Teilchen wird von anderem Teilchen übernommen und um einen Faktor reduziert
Parameters
node
newnode
Definition at line 209 of file soundwavefunction.c.
References getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), and setFreq6000b10000().
Referenced by procedure(), and procedureH().
void setMovement (item_node * node, int m)
Setter für Movement
Parameters
node
m
Definition at line 35 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by copyMovement(), createItem(), and createReceipt().
void setSideOfWave (item_node * node, int side)
Legt die Seite der Welle für ein SoundItem fest
Parameters
node betroffenes Item
side Seite der `Welle` 0 = nicht von betroffen , 1 == Links , 2 = Rechts, 3 = Oben, 4 = Unten
Definition at line 161 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by changeReboundSideOfWave(), createReceipt(), interference(), loudspeaker(), main(), procedure(), and procedureH().
void setTouche (item_node * node)
Touched Element...
Parameters
node
Definition at line 70 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by addWave(), createReceipt(), procedure(), and procedureH().
void setWaveRoot (item_node * node, item_node * rootnode)
Definition at line 51 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by interference(), and procedureH().
void unTouche (item_node * node)
Untouched Element...
Parameters
node
Definition at line 79 of file soundwavefunction.c.
References item_node::data, getItemID(), and item_node::Sound.
Referenced by unToucheAll().
void unToucheAll ()
Untouched alle Elemente
Definition at line 87 of file soundwavefunction.c.
References getItem_Root(), getItemID(), i, j, k, item_node::next, unTouche(), x_format, y_format, and z_format.
Referenced by main().
Variable Documentation
int j
Definition at line 7 of file soundwavefunction.c.
Referenced by unToucheAll().
int k
Definition at line 7 of file soundwavefunction.c.
Referenced by unToucheAll().
int l
Definition at line 7 of file soundwavefunction.c.