.TH "item_node" 3 "Wed Sep 30 2015" "SoundSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
item_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "struct \fBitem_node\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBitem_node\fP * \fBprev\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBfreq_20_40\fP"
.br
.ti -1c
.RI "      int \fBfreq_40_100\fP"
.br
.ti -1c
.RI "      int \fBfreq_100_150\fP"
.br
.ti -1c
.RI "      int \fBfreq_150_400\fP"
.br
.ti -1c
.RI "      int \fBfreq_400_1000\fP"
.br
.ti -1c
.RI "      int \fBfreq_1000_2000\fP"
.br
.ti -1c
.RI "      int \fBfreq_2000_3500\fP"
.br
.ti -1c
.RI "      int \fBfreq_3500_6000\fP"
.br
.ti -1c
.RI "      int \fBfreq_6000_10000\fP"
.br
.ti -1c
.RI "      int \fBfreq_10000_20000\fP"
.br
.ti -1c
.RI "      bool \fBtouched\fP"
.br
.ti -1c
.RI "      int \fBdirection_id\fP"
.br
.ti -1c
.RI "      int \fBmovement\fP"
.br
.ti -1c
.RI "      int \fBsideofwave\fP"
.br
.ti -1c
.RI "      struct \fBitem_node\fP * \fBwaveroot\fP"
.br
.ti -1c
.RI "   } \fBSound\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      float \fBreduce\fP"
.br
.ti -1c
.RI "   } \fBObstacle\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Alle Elemente werden in Form dieses Structs repräsentiert 
.PP
Definition at line 10 of file main\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. }   item_node::data"

.PP
Referenced by getDirectionID(), getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), getMovement(), getSideOfWave(), getTouch(), getWaveRoot(), increaseMovement(), main(), setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), setMovement(), setSideOfWave(), setTouche(), setWaveRoot(), and unTouche()\&.
.SS "int item_node::direction_id"

.PP
Definition at line 28 of file main\&.h\&.
.SS "int item_node::freq_10000_20000"

.PP
Definition at line 26 of file main\&.h\&.
.SS "int item_node::freq_1000_2000"

.PP
Definition at line 22 of file main\&.h\&.
.SS "int item_node::freq_100_150"

.PP
Definition at line 19 of file main\&.h\&.
.SS "int item_node::freq_150_400"

.PP
Definition at line 20 of file main\&.h\&.
.SS "int item_node::freq_2000_3500"

.PP
Definition at line 23 of file main\&.h\&.
.SS "int item_node::freq_20_40"

.PP
Definition at line 17 of file main\&.h\&.
.SS "int item_node::freq_3500_6000"

.PP
Definition at line 24 of file main\&.h\&.
.SS "int item_node::freq_400_1000"

.PP
Definition at line 21 of file main\&.h\&.
.SS "int item_node::freq_40_100"

.PP
Definition at line 18 of file main\&.h\&.
.SS "int item_node::freq_6000_10000"

.PP
Definition at line 25 of file main\&.h\&.
.SS "int item_node::id"

.PP
Definition at line 12 of file main\&.h\&.
.PP
Referenced by createItem(), createRoom(), createRoomNew(), getFieldID(), getItem_Root(), getItem_RootNewRoom(), getItemID(), isObstacle(), isSoundField(), and setItemID()\&.
.SS "int item_node::movement"

.PP
Definition at line 34 of file main\&.h\&.
.SS "struct \fBitem_node\fP* item_node::next"

.PP
Definition at line 13 of file main\&.h\&.
.PP
Referenced by addItem(), addItemNewRoom(), createItem(), createRoom(), createRoomNew(), getFieldID(), getItem_Root(), getItem_RootNewRoom(), interference(), main(), removeItem(), saveVisualisation(), and unToucheAll()\&.
.SS "struct { \&.\&.\&. }   item_node::Obstacle"

.SS "struct \fBitem_node\fP* item_node::prev"

.PP
Definition at line 14 of file main\&.h\&.
.PP
Referenced by addItem(), addItemNewRoom(), createItem(), and removeItem()\&.
.SS "float item_node::reduce"

.PP
Definition at line 39 of file main\&.h\&.
.SS "int item_node::sideofwave"

.PP
Definition at line 35 of file main\&.h\&.
.SS "struct { \&.\&.\&. }   item_node::Sound"

.PP
Referenced by getDirectionID(), getFreq10000b20000(), getFreq1000b2000(), getFreq100b150(), getFreq150b400(), getFreq2000b3500(), getFreq20b40(), getFreq3500b6000(), getFreq400b1000(), getFreq40b100(), getFreq6000b10000(), getMovement(), getSideOfWave(), getTouch(), getWaveRoot(), increaseMovement(), main(), setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), setMovement(), setSideOfWave(), setTouche(), setWaveRoot(), and unTouche()\&.
.SS "bool item_node::touched"

.PP
Definition at line 27 of file main\&.h\&.
.SS "struct \fBitem_node\fP* item_node::waveroot"

.PP
Definition at line 36 of file main\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SoundSim from the source code\&.
