.TH "minunit.h" 3 "Wed Sep 30 2015" "SoundSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minunit.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmu_assert\fP(message,  test)   do { if (!(test)) return message; } while (0)"
.br
.ti -1c
.RI "#define \fBmu_run_test\fP(test)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBtests_run\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define mu_assert(message, test)   do { if (!(test)) return message; } while (0)"

.PP
Definition at line 2 of file minunit\&.h\&.
.PP
Referenced by testGetItemID()\&.
.SS "#define mu_run_test(test)"
\fBValue:\fP
.PP
.nf
do { char *message = test(); tests_run++; \
                                if (message) return message; } while (0)
.fi
.PP
Definition at line 3 of file minunit\&.h\&.
.PP
Referenced by all_tests()\&.
.SH "Variable Documentation"
.PP 
.SS "int tests_run"

.PP
Definition at line 10 of file minunit_soundsim\&.c\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SoundSim from the source code\&.
