.TH "minunit_soundsim.c" 3 "Wed Sep 30 2015" "SoundSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
minunit_soundsim.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'soundwavefunction\&.h'\fP
.br
\fC#include 'collision\&.h'\fP
.br
\fC#include 'minunit\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char * \fBtestGetItemID\fP ()"
.br
.ti -1c
.RI "static char * \fBall_tests\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBtests_run\fP = 0"
.br
.ti -1c
.RI "int \fBx_format\fP = 100"
.br
.RI "\fIRaum Formate\&. \fP"
.ti -1c
.RI "int \fBy_format\fP = 100"
.br
.ti -1c
.RI "int \fBz_format\fP = 100"
.br
.ti -1c
.RI "\fBitem_node\fP *** \fBroom\fP"
.br
.ti -1c
.RI "\fBitem_node\fP *** \fBroom_new\fP"
.br
.ti -1c
.RI "\fBitem_node\fP * \fBtest1\fP"
.br
.ti -1c
.RI "\fBitem_node\fP * \fBtest2\fP"
.br
.ti -1c
.RI "\fBitem_node\fP * \fBtest3\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static char* all_tests ()\fC [static]\fP"

.PP
Definition at line 27 of file minunit_soundsim\&.c\&.
.PP
References mu_run_test, and testGetItemID()\&.
.PP
Referenced by main()\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 33 of file minunit_soundsim\&.c\&.
.PP
References all_tests(), createItem(), createRoom(), setDirectionID(), setFreq10000b20000(), setFreq1000b2000(), setFreq100b150(), setFreq150b400(), setFreq2000b3500(), setFreq20b40(), setFreq3500b6000(), setFreq400b1000(), setFreq40b100(), setFreq6000b10000(), setSideOfWave(), tests_run, x_format, and y_format\&.
.SS "static char* testGetItemID ()\fC [static]\fP"

.PP
Definition at line 21 of file minunit_soundsim\&.c\&.
.PP
References getItemID(), and mu_assert\&.
.PP
Referenced by all_tests()\&.
.SH "Variable Documentation"
.PP 
.SS "\fBitem_node\fP*** room"

.PP
Definition at line 14 of file minunit_soundsim\&.c\&.
.SS "\fBitem_node\fP*** room_new"

.PP
Definition at line 15 of file minunit_soundsim\&.c\&.
.SS "\fBitem_node\fP* test1"

.PP
Definition at line 16 of file minunit_soundsim\&.c\&.
.SS "\fBitem_node\fP* test2"

.PP
Definition at line 17 of file minunit_soundsim\&.c\&.
.SS "\fBitem_node\fP* test3"

.PP
Definition at line 18 of file minunit_soundsim\&.c\&.
.SS "int tests_run = 0"

.PP
Definition at line 10 of file minunit_soundsim\&.c\&.
.PP
Referenced by main()\&.
.SS "int x_format = 100"

.PP
Raum Formate\&. 
.PP
Definition at line 11 of file minunit_soundsim\&.c\&.
.PP
Referenced by main()\&.
.SS "int y_format = 100"

.PP
Definition at line 12 of file minunit_soundsim\&.c\&.
.PP
Referenced by main()\&.
.SS "int z_format = 100"

.PP
Definition at line 13 of file minunit_soundsim\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SoundSim from the source code\&.
